services:
  # Firestore Emulator
  firestore:
    image: google/cloud-sdk:alpine
    command: gcloud --quiet beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8081:8080"
    environment:
      - CLOUDSDK_CORE_PROJECT=todo-project

  # Todo API
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - PROJECT_ID=todo-project
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - LOG_LEVEL=debug
    depends_on:
      - firestore
    restart: always
